#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-multi_xml
Version  : 0.5.5
Release  : 7
URL      : https://rubygems.org/downloads/multi_xml-0.5.5.gem
Source0  : https://rubygems.org/downloads/multi_xml-0.5.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-simplecov

%description
# MultiXML
[![Gem Version](https://badge.fury.io/rb/multi_xml.png)][gem]
[![Build Status](https://secure.travis-ci.org/sferik/multi_xml.png?branch=master)][travis]
[![Dependency Status](https://gemnasium.com/sferik/multi_xml.png?travis)][gemnasium]
[![Code Climate](https://codeclimate.com/github/sferik/multi_xml.png)][codeclimate]
[![Coverage Status](https://coveralls.io/repos/sferik/multi_xml/badge.png?branch=master)][coveralls]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n multi_xml-0.5.5
gem spec %{SOURCE0} -l --ruby > rubygem-multi_xml.gemspec

%build
gem build rubygem-multi_xml.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
multi_xml-0.5.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/multi_xml-0.5.5
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/multi_xml-0.5.5.gem
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/LICENSE.md
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/README.md
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/lib/multi_xml.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/libxml.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/libxml2_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/nokogiri.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/ox.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/lib/multi_xml/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/multi_xml.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/spec/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/spec/multi_xml_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/spec/parser_shared_example.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_xml-0.5.5/spec/speed.rb
/usr/lib64/ruby/gems/2.3.0/specifications/multi_xml-0.5.5.gemspec
